
export const AUTH_LOGIN_REQUEST = 'AUTH/LOGIN_REQUEST'
export const AUTH_LOGIN_ERROR = 'AUTH/LOGIN_ERROR'
export const AUTH_LOGGED_IN = 'AUTH/LOGGED_IN'
export const AUTH_LOGGED_OUT = 'AUTH/LOGGED_OUT'

export const AUTH_SIGNUP_REQUEST = 'AUTH/SIGNUP_REQUEST'
export const AUTH_SIGNUP_ERROR = 'AUTH/SIGNUP_ERROR'

export const PROFILE_FETCH_REQUEST = 'PROFILE/FETCH_REQUEST'
export const PROFILE_FETCH_SUCCESS = 'PROFILE/FETCH_SUCCESS'
export const PROFILE_FETCH_FAILURE = 'PROFILE/FETCH_FAILURE'

export const ENTRIES_FETCH_REQUEST = 'ENTRIES/FETCH_REQUEST'
export const ENTRIES_FETCH_SUCCESS = 'ENTRIES/FETCH_SUCCESS'
export const ENTRIES_FETCH_FAILURE = 'ENTRIES/FETCH_FAILURE'

export const ENTRIES_ADD_REQUEST = 'ENTRIES/ADD_REQUEST'
export const ENTRIES_ADD_SUCCESS = 'ENTRIES/ADD_SUCCESS'
export const ENTRIES_ADD_FAILURE = 'ENTRIES/ADD_FAILURE'

export const ENTRIES_TOGGLE_SELECTION = 'ENTRIES/TOGGLE_SELECTION'
export const ENTRIES_UPDATE = 'ENTRIES/UPDATE'
export const ENTRIES_DELETE = 'ENTRIES/DELETE'

export const CATEGORIES_FETCH_REQUEST = 'CATEGORIES/FETCH_REQUEST'
export const CATEGORIES_FETCH_SUCCESS = 'CATEGORIES/FETCH_SUCCESS'
export const CATEGORIES_FETCH_FAILURE = 'CATEGORIES/FETCH_FAILURE'

export const ERROR_CLIENT = 'ERROR_CLIENT'
export const ERROR_SERVER = 'ERROR_SERVER'
